"""empty message

Revision ID: 1ad08357acbb
Revises: 835dac52c59b
Create Date: 2021-05-11 14:09:51.926317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ad08357acbb'
down_revision = '835dac52c59b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_item_permissao',
    sa.Column('pri_id', sa.Integer(), nullable=False),
    sa.Column('pri_nome', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('pri_id'),
    sa.UniqueConstraint('pri_nome')
    )
    op.create_table('tbl_usuarios',
    sa.Column('usu_id', sa.Integer(), nullable=False),
    sa.Column('usu_nome', sa.String(length=100), nullable=True),
    sa.Column('usu_email', sa.String(length=200), nullable=True),
    sa.Column('usu_usuario', sa.String(length=60), nullable=True),
    sa.Column('usu_senha', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('usu_id'),
    sa.UniqueConstraint('usu_email'),
    sa.UniqueConstraint('usu_nome')
    )
    op.create_table('tbl_permissoes',
    sa.Column('prm_id', sa.Integer(), nullable=False),
    sa.Column('prm_usuario', sa.Integer(), nullable=False),
    sa.Column('prm_item_permitido', sa.Integer(), nullable=False),
    sa.Column('prm_inserir', sa.SmallInteger(), nullable=True),
    sa.Column('prm_alterar', sa.SmallInteger(), nullable=True),
    sa.Column('prm_deletar', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['prm_item_permitido'], ['tbl_item_permissao.pri_id'], ),
    sa.ForeignKeyConstraint(['prm_usuario'], ['tbl_usuarios.usu_id'], ),
    sa.PrimaryKeyConstraint('prm_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_permissoes')
    op.drop_table('tbl_usuarios')
    op.drop_table('tbl_item_permissao')
    # ### end Alembic commands ###
