"""empty message

Revision ID: 835dac52c59b
Revises: 
Create Date: 2021-05-03 14:28:19.395659

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '835dac52c59b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_item_permissao')
    op.drop_table('tbl_permissoes')
    op.drop_table('tbl_categoria')
    op.drop_table('tbl_campus')
    op.drop_table('tbl_periodos')
    op.drop_table('tbl_eventos')
    op.alter_column('tbl_usuarios', 'usu_email',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('tbl_usuarios', 'usu_nome',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('tbl_usuarios', 'usu_senha',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('tbl_usuarios', 'usu_usuario',
               existing_type=mysql.VARCHAR(length=60),
               nullable=True)
    op.drop_index('usu_id_2', table_name='tbl_usuarios')
    op.create_index(op.f('ix_tbl_usuarios_usu_email'), 'tbl_usuarios', ['usu_email'], unique=True)
    op.create_index(op.f('ix_tbl_usuarios_usu_nome'), 'tbl_usuarios', ['usu_nome'], unique=True)
    op.create_index(op.f('ix_tbl_usuarios_usu_usuario'), 'tbl_usuarios', ['usu_usuario'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_usuarios_usu_usuario'), table_name='tbl_usuarios')
    op.drop_index(op.f('ix_tbl_usuarios_usu_nome'), table_name='tbl_usuarios')
    op.drop_index(op.f('ix_tbl_usuarios_usu_email'), table_name='tbl_usuarios')
    op.create_index('usu_id_2', 'tbl_usuarios', ['usu_id'], unique=False)
    op.alter_column('tbl_usuarios', 'usu_usuario',
               existing_type=mysql.VARCHAR(length=60),
               nullable=False)
    op.alter_column('tbl_usuarios', 'usu_senha',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('tbl_usuarios', 'usu_nome',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('tbl_usuarios', 'usu_email',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.create_table('tbl_eventos',
    sa.Column('eve_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('eve_periodo', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('eve_campus', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('eve_categoria', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('eve_nome', mysql.VARCHAR(collation='utf8_swedish_ci', length=255), nullable=False),
    sa.Column('eve_local', mysql.VARCHAR(collation='utf8_swedish_ci', length=255), nullable=False),
    sa.Column('eve_data_ini', mysql.DATETIME(), nullable=False),
    sa.Column('eve_data_fim', mysql.DATETIME(), nullable=False),
    sa.Column('eve_descricao', mysql.MEDIUMTEXT(collation='utf8_swedish_ci'), nullable=False),
    sa.Column('eve_url', mysql.VARCHAR(collation='utf8_swedish_ci', length=255), nullable=False),
    sa.PrimaryKeyConstraint('eve_id'),
    mysql_collate='utf8_swedish_ci',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('tbl_periodos',
    sa.Column('prd_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('prd_nome', mysql.VARCHAR(collation='utf8_swedish_ci', length=20), nullable=False),
    sa.Column('prd_data_ini', mysql.DATETIME(), nullable=False),
    sa.Column('prd_data_fim', mysql.DATETIME(), nullable=False),
    sa.Column('prd_url', mysql.TEXT(collation='utf8_swedish_ci'), nullable=True),
    sa.PrimaryKeyConstraint('prd_id'),
    mysql_collate='utf8_swedish_ci',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('tbl_campus',
    sa.Column('cps_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('cps_nome', mysql.VARCHAR(collation='utf8mb4_swedish_ci', length=100), nullable=False),
    sa.PrimaryKeyConstraint('cps_id'),
    mysql_collate='utf8mb4_swedish_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_table('tbl_categoria',
    sa.Column('cat_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('cat_nome', mysql.VARCHAR(collation='utf8_swedish_ci', length=100), nullable=False),
    sa.Column('cat_cor', mysql.VARCHAR(collation='utf8_swedish_ci', length=8), nullable=False),
    sa.PrimaryKeyConstraint('cat_id'),
    mysql_collate='utf8_swedish_ci',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('tbl_permissoes',
    sa.Column('prm_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('prm_usuario', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('prm_item_permitido', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('prm_inserir', mysql.SMALLINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('prm_alterar', mysql.SMALLINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('prm_deletar', mysql.SMALLINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('prm_id'),
    mysql_default_charset='latin1',
    mysql_engine='MyISAM'
    )
    op.create_table('tbl_item_permissao',
    sa.Column('pri_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('pri_nome_menu', mysql.VARCHAR(collation='utf8_swedish_ci', length=100), nullable=False),
    sa.PrimaryKeyConstraint('pri_id'),
    mysql_collate='utf8_swedish_ci',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    # ### end Alembic commands ###
