"""empty message

Revision ID: 8d10bf2b8e02
Revises: f89cf48d31e9
Create Date: 2021-06-26 18:13:39.458930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d10bf2b8e02'
down_revision = 'f89cf48d31e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_comentarios',
    sa.Column('com_id', sa.Integer(), nullable=False),
    sa.Column('com_nome', sa.String(length=40), nullable=False),
    sa.Column('com_email', sa.String(length=40), nullable=True),
    sa.Column('com_texto', sa.Text(), nullable=False),
    sa.Column('com_nota', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('com_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_comentarios')
    # ### end Alembic commands ###
