"""empty message

Revision ID: b6b880adabd6
Revises: 8d10bf2b8e02
Create Date: 2021-06-26 18:32:15.928916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6b880adabd6'
down_revision = '8d10bf2b8e02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_comentarios', sa.Column('com_curso', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_comentarios', 'com_curso')
    # ### end Alembic commands ###
