"""empty message

Revision ID: c99e2066e60a
Revises: 2a92ba210afc
Create Date: 2021-05-11 18:55:44.351328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c99e2066e60a'
down_revision = '2a92ba210afc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_categoria',
    sa.Column('cat_id', sa.Integer(), nullable=False),
    sa.Column('cat_nome', sa.String(length=100), nullable=False),
    sa.Column('cat_cor', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('cat_id'),
    sa.UniqueConstraint('cat_nome')
    )
    op.create_table('tbl_item_permissao',
    sa.Column('pri_id', sa.Integer(), nullable=False),
    sa.Column('pri_nome', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('pri_id'),
    sa.UniqueConstraint('pri_nome')
    )
    op.create_table('tbl_periodos',
    sa.Column('prd_id', sa.Integer(), nullable=False),
    sa.Column('prd_nome', sa.String(length=20), nullable=False),
    sa.Column('prd_data_ini', sa.DateTime(), nullable=False),
    sa.Column('prd_data_fim', sa.DateTime(), nullable=False),
    sa.Column('prd_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('prd_id'),
    sa.UniqueConstraint('prd_nome')
    )
    op.create_table('tbl_usuarios',
    sa.Column('usu_id', sa.Integer(), nullable=False),
    sa.Column('usu_nome', sa.String(length=100), nullable=False),
    sa.Column('usu_email', sa.String(length=200), nullable=False),
    sa.Column('usu_usuario', sa.String(length=60), nullable=False),
    sa.Column('usu_senha', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('usu_id'),
    sa.UniqueConstraint('usu_email'),
    sa.UniqueConstraint('usu_nome')
    )
    op.create_table('tbl_eventos',
    sa.Column('eve_id', sa.Integer(), nullable=False),
    sa.Column('eve_periodo', sa.Integer(), nullable=False),
    sa.Column('eve_categoria', sa.Integer(), nullable=False),
    sa.Column('eve_nome', sa.String(length=255), nullable=False),
    sa.Column('eve_local', sa.String(length=255), nullable=False),
    sa.Column('eve_data_ini', sa.DateTime(), nullable=False),
    sa.Column('eve_data_fim', sa.DateTime(), nullable=False),
    sa.Column('eve_descricao', sa.Text(), nullable=False),
    sa.Column('eve_url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['eve_categoria'], ['tbl_categoria.cat_id'], ),
    sa.ForeignKeyConstraint(['eve_periodo'], ['tbl_periodos.prd_id'], ),
    sa.PrimaryKeyConstraint('eve_id')
    )
    op.create_table('tbl_permissoes',
    sa.Column('prm_id', sa.Integer(), nullable=False),
    sa.Column('prm_usuario', sa.Integer(), nullable=False),
    sa.Column('prm_item_permitido', sa.Integer(), nullable=False),
    sa.Column('prm_inserir', sa.SmallInteger(), nullable=True),
    sa.Column('prm_alterar', sa.SmallInteger(), nullable=True),
    sa.Column('prm_deletar', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['prm_item_permitido'], ['tbl_item_permissao.pri_id'], ),
    sa.ForeignKeyConstraint(['prm_usuario'], ['tbl_usuarios.usu_id'], ),
    sa.PrimaryKeyConstraint('prm_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_permissoes')
    op.drop_table('tbl_eventos')
    op.drop_table('tbl_usuarios')
    op.drop_table('tbl_periodos')
    op.drop_table('tbl_item_permissao')
    op.drop_table('tbl_categoria')
    # ### end Alembic commands ###
