"""empty message

Revision ID: f89cf48d31e9
Revises: 9ddfdef074e6
Create Date: 2021-05-22 09:54:44.549820

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f89cf48d31e9'
down_revision = '9ddfdef074e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_item_permissao', sa.Column('pri_nome_menu', sa.String(length=200), nullable=False))
    op.drop_index('pri_nome', table_name='tbl_item_permissao')
    op.drop_index('pri_nome_2', table_name='tbl_item_permissao')
    op.create_unique_constraint(None, 'tbl_item_permissao', ['pri_nome_menu'])
    op.drop_column('tbl_item_permissao', 'pri_nome')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_item_permissao', sa.Column('pri_nome', mysql.VARCHAR(collation='utf8_swedish_ci', length=200), nullable=False))
    op.drop_constraint(None, 'tbl_item_permissao', type_='unique')
    op.create_index('pri_nome_2', 'tbl_item_permissao', ['pri_nome'], unique=False)
    op.create_index('pri_nome', 'tbl_item_permissao', ['pri_nome'], unique=False)
    op.drop_column('tbl_item_permissao', 'pri_nome_menu')
    # ### end Alembic commands ###
